### ISSUE TITLE
"Version of nucmer too low. I found ., but must be at least 3.1."

### ISSUE THREAD

**Issue by MattPinder** [sanger-pathogens/circlator#127]
Thank you for addressing my previous issue with nucmer detection ([#122](https://github.com/sanger-pathogens/circlator/issues/122)). However, having installed v1.5.5, I'm now having a different nucmer-related problem. Once again, `circlator progcheck` finds the correct version of nucmer, however `circlator all` is detecting the version incorrectly (as opposed to not finding it at all previously). This is the error message I receive:

`Traceback (most recent call last):`
`  File "/usr/local/packages/anaconda3-4.4.0/bin/circlator", line 4, in <module>`
`    __import__('pkg_resources').run_script('circlator==1.5.5', 'circlator')`
`  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 744, in run_script`
`  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1499, in run_script`
`  File "/home/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.5-py3.6.egg/EGG-INFO/scripts/circlator", line 58, in <module>`
`    exec('circlator.tasks.' + task + '.run()')`
`  File "<string>", line 1, in <module>`
`  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.5-py3.6.egg/circlator/tasks/all.py", line 74, in run`
`    circlator.versions.get_all_versions(None, raise_error=True, assembler=options.assembler)`
`  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.5-py3.6.egg/circlator/versions.py", line 15, in get_all_versions`
`    external_progs.check_all_progs(verbose=False, raise_error=raise_error, filehandle=filehandle, debug=debug, assembler=assembler)`
`  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.5-py3.6.egg/circlator/external_progs.py", line 105, in check_all_progs`
`    make_and_check_prog(prog, verbose=verbose, raise_error=raise_error, filehandle=filehandle, debug=debug, required=prog==assembler)`
`  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.5-py3.6.egg/circlator/external_progs.py", line 82, in make_and_check_prog`
`    handle_error('Version of ' + name + ' too low. I found ' + p.version + ', but must be at least ' + min_versions[name] + '. Found here:\n' + p.from_which, raise_error=raise_error)`
`  File "/usr/local/packages/anaconda3-4.4.0/lib/python3.6/site-packages/circlator-1.5.5-py3.6.egg/circlator/external_progs.py", line 53, in handle_error`
`    raise Error(message + '\nCannot continue')`
**`circlator.external_progs.Error: Version of nucmer too low. I found ., but must be at least 3.1. Found here:
/usr/local/packages/MUMmer3.23/nucmer`**
`Cannot continue`

Once again, any guidance would be greatly appreciated.

**Comment by kimnegrette3** [comment]
Hi! did you solve this issue? I'm having the exact same problem now. 
Any help is really appreciated.
Thanks!

**Comment by MattPinder** [comment]
Going back through my notes, it appears that my last reference to Circlator was 'Waiting on reply from devs'...
If I return to this and have any success in installing it, I'll be sure to post my solution here. I hope you'll have more luck than I did in the meantime

**Comment by kimnegrette3** [comment]
Hi @MattPinder! Thak you for taking the time to reply! In case you need to run circlator again, I think I managed to solve this nucmer problem. I downloaded the bioconda package and modified the external_progs.py file in the "prog_to_version_cmd" section so the nucmer line finally looks like this: 

'nucmer': ('--version', re.compile(r'^NUCmer \(NUCleotide MUMmer\) version ([0-9\.]+)')),

This is something like the solution proposed on #110 

That solved the initial problem, but I'm still waiting for the complete pipeline to finish. Hope it works till the end.
