### ISSUE TITLE
Install failed - bio-assembly-refinement/setup.py", line 6,

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/circlator#13]
Any ideas?

```
tseemann@marvin:~ $ pip3 install circlator
You are using pip version 6.1.1, however version 7.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting circlator
  Downloading circlator-0.12.1.tar.gz (80kB)
    100% |████████████████████████████████| 81kB 1.2MB/s
Collecting nose>=1.3 (from circlator)
  Downloading nose-1.3.6-py3-none-any.whl (154kB)
    100% |████████████████████████████████| 155kB 1.8MB/s
Collecting openpyxl (from circlator)
  Downloading openpyxl-2.2.3.tar.gz (108kB)
    100% |████████████████████████████████| 110kB 1.3MB/s
Collecting pyfastaq>=3.5.0 (from circlator)
  Downloading pyfastaq-3.5.0.tar.gz (47kB)
    100% |████████████████████████████████| 49kB 2.9MB/s
Requirement already satisfied (use --upgrade to upgrade): pysam>=0.8.1 in /bio/linuxbrew/lib/python3.4/site-packages (from circlator)
Collecting pymummer>=0.2.0 (from circlator)
  Downloading pymummer-0.3.0.tar.gz
Collecting bio-assembly-refinement>=0.1.0 (from circlator)
  Downloading bio_assembly_refinement-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-uj4icwuj/bio-assembly-refinement/setup.py", line 12, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-build-uj4icwuj/bio-assembly-refinement/setup.py", line 6, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-uj4icwuj/bio-assembly-refinement/README.md'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-uj4icwuj/bio-assembly-refinement
```

**Comment by nds** [comment]
Hi

Thank you for your email. I'm having a look.

Nishadi

--
Dr. Nishadi De Silva
Senior Software Developer
Pathogen Informatics 
Wellcome Trust Sanger Institute
Cambridgeshire, UK

Phone: +44 (0)1223 494798

**Comment by nds** [comment]
Hi Torsten

Thank you for letting us know about this. It's now all fixed.

Nishadi
--
Dr. Nishadi De Silva
Senior Software Developer
Pathogen Informatics 
Wellcome Trust Sanger Institute
Cambridgeshire, UK

Phone: +44 (0)1223 494798
