### ISSUE TITLE
Circlator python3 setup.py test errors

### ISSUE THREAD

**Issue by pichiapastoris** [sanger-pathogens/circlator#130]
Dear Developers:

I got 8 error messages while trying to install the circlator 1.5.5 into my Ununtu (16.04 LTS) in the virtual box. All the dependencies were successfully installed as I could tell. The way I tried to install circlator is to download the latest release from the github repository and followed the instruction on the page (http://sanger-pathogens.github.io/circlator). According to this page, if I downloaded it, I had to run python3 setup.py test to see if the tests can pass. Here is where my questions are from. They didn't completely pass.

I had tried to fix several errors, but there are still 8 showed up and I really couldn't find any information online to fix that. Thus, I am sharing the error messages here and hope someone can give me some advice. (I don't have strong back ground on coding, so I may ask some questions very easy to resolve though...)

Thank you in advance!

Here are my error messages that I got:

======================================================================
ERROR: test_build_spades_kmers (assemble_test.TestAssemble)
test _build_spades_kmers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pwd/circlator-1.5.5/circlator/tests/assemble_test.py", line 17, in setUp
    self.tmp_assemble_dir
  File "/home/pwd/circlator-1.5.5/circlator/assemble.py", line 30, in __init__
    self.samtools = external_progs.make_and_check_prog('samtools', verbose=self.verbose)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 78, in make_and_check_prog
    handle_error('Found ' + name + " but couldn't get version.", raise_error=raise_error)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 53, in handle_error
    raise Error(message + '\nCannot continue')
circlator.external_progs.Error: Found samtools but couldn't get version.
Cannot continue

======================================================================
ERROR: test_make_canu_command (assemble_test.TestAssemble)
test _make_canu_command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pwd/circlator-1.5.5/circlator/tests/assemble_test.py", line 17, in setUp
    self.tmp_assemble_dir
  File "/home/pwd/circlator-1.5.5/circlator/assemble.py", line 30, in __init__
    self.samtools = external_progs.make_and_check_prog('samtools', verbose=self.verbose)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 78, in make_and_check_prog
    handle_error('Found ' + name + " but couldn't get version.", raise_error=raise_error)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 53, in handle_error
    raise Error(message + '\nCannot continue')
circlator.external_progs.Error: Found samtools but couldn't get version.
Cannot continue

======================================================================
ERROR: test_make_spades_command (assemble_test.TestAssemble)
test _make_spades_command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pwd/circlator-1.5.5/circlator/tests/assemble_test.py", line 17, in setUp
    self.tmp_assemble_dir
  File "/home/pwd/circlator-1.5.5/circlator/assemble.py", line 30, in __init__
    self.samtools = external_progs.make_and_check_prog('samtools', verbose=self.verbose)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 78, in make_and_check_prog
    handle_error('Found ' + name + " but couldn't get version.", raise_error=raise_error)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 53, in handle_error
    raise Error(message + '\nCannot continue')
circlator.external_progs.Error: Found samtools but couldn't get version.
Cannot continue

======================================================================
ERROR: test_rename_canu_contigs (assemble_test.TestAssemble)
test _rename_canu_contigs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pwd/circlator-1.5.5/circlator/tests/assemble_test.py", line 17, in setUp
    self.tmp_assemble_dir
  File "/home/pwd/circlator-1.5.5/circlator/assemble.py", line 30, in __init__
    self.samtools = external_progs.make_and_check_prog('samtools', verbose=self.verbose)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 78, in make_and_check_prog
    handle_error('Found ' + name + " but couldn't get version.", raise_error=raise_error)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 53, in handle_error
    raise Error(message + '\nCannot continue')
circlator.external_progs.Error: Found samtools but couldn't get version.
Cannot continue

======================================================================
ERROR: test_bwa_index (mapping_test.TestMapping)
test bwa_index
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pwd/circlator-1.5.5/circlator/tests/mapping_test.py", line 18, in test_bwa_index
    mapping.bwa_index(ref, outprefix)
  File "/home/pwd/circlator-1.5.5/circlator/mapping.py", line 20, in bwa_index
    bwa = external_progs.make_and_check_prog('bwa', verbose=verbose)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 72, in make_and_check_prog
    handle_error("WARNING: Didn't find " + name + " in path. Looked for:" + p.path, raise_error=die)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 53, in handle_error
    raise Error(message + '\nCannot continue')
circlator.external_progs.Error: WARNING: Didn't find bwa in path. Looked for:bwa
Cannot continue

======================================================================
ERROR: test_bwa_mem (mapping_test.TestMapping)
test bwa_mem
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pwd/circlator-1.5.5/circlator/tests/mapping_test.py", line 47, in test_bwa_mem
    mapping.bwa_mem(ref, reads, outfile)
  File "/home/pwd/circlator-1.5.5/circlator/mapping.py", line 55, in bwa_mem
    samtools = external_progs.make_and_check_prog('samtools', verbose=verbose)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 78, in make_and_check_prog
    handle_error('Found ' + name + " but couldn't get version.", raise_error=raise_error)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 53, in handle_error
    raise Error(message + '\nCannot continue')
circlator.external_progs.Error: Found samtools but couldn't get version.
Cannot continue

======================================================================
ERROR: test_index_fasta (merge_test.TestMerge)
test _index_fasta
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pwd/circlator-1.5.5/circlator/tests/merge_test.py", line 549, in test_index_fasta
    self.merger._index_fasta(test_fa)
  File "/home/pwd/circlator-1.5.5/circlator/merge.py", line 632, in _index_fasta
    samtools = circlator.external_progs.make_and_check_prog('samtools')
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 78, in make_and_check_prog
    handle_error('Found ' + name + " but couldn't get version.", raise_error=raise_error)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 53, in handle_error
    raise Error(message + '\nCannot continue')
circlator.external_progs.Error: Found samtools but couldn't get version.
Cannot continue

======================================================================
ERROR: test_write_act_files (merge_test.TestMerge)
test _write_act_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pwd/circlator-1.5.5/circlator/tests/merge_test.py", line 574, in test_write_act_files
    self.merger._write_act_files(ref_fasta, qry_fasta, coords_file, outprefix)
  File "/home/pwd/circlator-1.5.5/circlator/merge.py", line 644, in _write_act_files
    self._index_fasta(ref_fasta)
  File "/home/pwd/circlator-1.5.5/circlator/merge.py", line 632, in _index_fasta
    samtools = circlator.external_progs.make_and_check_prog('samtools')
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 78, in make_and_check_prog
    handle_error('Found ' + name + " but couldn't get version.", raise_error=raise_error)
  File "/home/pwd/circlator-1.5.5/circlator/external_progs.py", line 53, in handle_error
    raise Error(message + '\nCannot continue')
circlator.external_progs.Error: Found samtools but couldn't get version.
Cannot continue

----------------------------------------------------------------------
Ran 115 tests in 1.876s

FAILED (errors=8, skipped=6)
Test failed: <unittest.runner.TextTestResult run=115 errors=8 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=115 errors=8 failures=0>

**Comment by bhill-17** [comment]
Did you ever get any help with resolving this issue?
