### ISSUE TITLE
Assembler canu run gets terminated 

### ISSUE THREAD

**Issue by Rmmendoza** [sanger-pathogens/circlator#177]
Hello, I am trying to run circlator using canu (v 1.9)as the assembler

circlator all --assembler canu ~/Desktop/CANU/KU15176/assembly/KU15176.contigs.fasta ~/Desktop/CANU/KU15176/corrected_KU15176/KU15176.correctedReads.fasta.gz ~/Desktop/Circulator_KU15176CANU

however the run gets terminated and I am getting the following error:
Traceback (most recent call last):
  File "/usr/bin/circlator", line 58, in <module>
    exec('circlator.tasks.' + task + '.run()')
  File "<string>", line 1, in <module>
  File "/home/rem/.local/lib/python3.8/site-packages/circlator/tasks/all.py", line 169, in run
    a.run()
  File "/home/rem/.local/lib/python3.8/site-packages/circlator/assemble.py", line 179, in run
    self.run_canu()
  File "/home/rem/.local/lib/python3.8/site-packages/circlator/assemble.py", line 172, in run_canu
    os.rename(original_gfa, renamed_gfa)
FileNotFoundError: [Errno 2] No such file or directory: '/home/rem/Desktop/Circulator_KU15176CANU/03.assemble/canu.contigs.gfa' -> '/home/rem/Desktop/Circulator_KU15176CANU/03.assemble/contigs.gfa'

Can anybody help me on this? your assistance will be greatly appreciated.
Thank you very much!

**Comment by youngDouble** [comment]
_Now that contigs.gfa got removed._ The `contigs.gfa` file has not been generated since` Canu v1.9`, downgrading canu should fix this error. see [circular contigs and contigs.gfa #1551](https://github.com/marbl/canu/issues/1551)
