### ISSUE TITLE
circlator Command Fails with ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by AymanMkhalifa** [sanger-pathogens/circlator#190]
I am trying to use circlator but encounter the following error when running the command:

circlator all --threads 4 --verbose canu_outdir/canu.contigs.fasta canu_outdir/canu.correctedReads.fasta.gz circlator_outdir --debug

Steps to Reproduce:

    Create a new conda environment: conda create -n fresh_circlator python=3.12
    Activate the environment: conda activate fresh_circlator
    Install circlator: pip install circlator
    Run the circlator command with the arguments provided.
    
    
    Error Message:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/circlator", line 57, in <module>
    exec('import circlator.tasks.' + task)
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/circlator/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution
ModuleNotFoundError: No module named 'pkg_resources'

Environment Details:

    Operating System: macOS 14.1
    Python Version: 3.12.4
    Conda Version: 23.5.2
    Circlator Version: 1.5.5

I have tried reinstalling setuptools and creating a fresh conda environment, but the issue persists. Any help would be appreciated.

**Comment by a-detiste** [comment]
Hi, I used this patch ... but I don't need to care for old Python versions:

https://salsa.debian.org/med-team/circlator/-/commit/e338e1d69c76aa5a2214e5ddbe10d327d07fa472
