### ISSUE TITLE
ImportError: No module named 'circlator'

### ISSUE THREAD

**Issue by chandni177** [sanger-pathogens/circlator#48]
Hi,

I tried installing Circlator and I'm getting stuck at this error. The test and install steps finish without any errors. However, when I try to run the prgcheck or circlator all commands, I get this error below -
 
```
[cdesai@endeavor ~]$ circlator 
Usage: circlator <command> [options] <required arguments>

To get minimal usage for a command use:
circlator command

To get full help for a command use one of:
circlator command -h
circlator command --help


Available commands:

all        Run mapreads, bam2reads, assemble, merge, clean, fixstart
mapreads   Map reads to assembly
bam2reads  Make reads from mapping to be reassembled
assemble   Run assembly using reads from bam2reads
merge      Merge original assembly and new assembly made by assemble
clean      Remove small and completely contained contigs from assembly
fixstart   Change start position of circular sequences
minimus2   Run the minimus2 based circularisation pipeline
get_dnaa   Download file of dnaA (or other of user's choice) genes
progcheck  Checks dependencies are installed
version    Print version and exit

[cdesai@endeavor ~]$ circlator all -h
Traceback (most recent call last):
  File "/usr/local/bin/circlator", line 4, in <module>
    __import__('pkg_resources').run_script('circlator==1.1.4', 'circlator')
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1621, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.4/site-packages/circlator-1.1.4-py3.4.egg/EGG-INFO/scripts/circlator", line 55, in <module>
  File "<string>", line 1, in <module>
ImportError: No module named 'circlator'
```

Could you tell me where this is going wrong?

Thank you,
Chandni

**Comment by martinghunt** [comment]
Hi Chandni,

Which method did you use to install it?

Can you confirm what happens if you start the python3 interpreter and try:
>>> import circlator

Thanks,
Martin

**Comment by chandni177** [comment]
Hi Martin,

I tried installing it using the github repository.

Here is the output -

```
[cdesai@endeavor src]$ python3.4
Python 3.4.3 (default, Feb 29 2016, 13:29:18) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import circlator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'circlator'
```

**Comment by martinghunt** [comment]
I presume you ran

    python3 setup.py test
    python3 setup.py install

For some reason, the place where it installs it isn't getting found by python. What's in your $PYTHONUSERBASE? I think for you it looks like it needs /usr/local/ in there, which would make python find /usr/local/lib/python3.4/sitepackages/*.

Alternatively, you could try a virtual environment like this:

    virtualenv -p $(which python3.4) venv_circlator
    source venv_circlator/bin/activate
    pip3 install circlator
