### ISSUE TITLE
error encountered when trying to install from the source

### ISSUE THREAD

**Issue by yjx1217** [sanger-pathogens/circlator#91]
Dear Martin,

I downloaded the most recent version ("circlator-1.5.1") of the circlator source code and tried to run the installation from the source. However, I encountered the following error immediately when running the "python3 setup.py test" command inside the uncompressed directory. Could you help to figure out what might be the cause of this error? Thanks in advance!

Best,
Jia-Xing

#########

> python3 setup.py test

running test
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 414, in fetch_build_egg
    cmd = self._egg_fetcher
AttributeError: 'Distribution' object has no attribute '_egg_fetcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 199, in run
    installed_dists = self.install_dists(self.distribution)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 194, in install_dists
    ir_d = dist.fetch_build_eggs(dist.install_requires or [])
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 373, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 417, in fetch_build_egg
    from setuptools.command.easy_install import easy_install
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 52, in <module>
    from setuptools.package_index import (
  File "/usr/lib/python2.7/site-packages/setuptools/package_index.py", line 18, in <module>
    from six.moves import urllib, http_client, configparser, map
  File "/usr/lib/python2.7/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/http/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

**Comment by andrewjpage** [comment]
Hi,
The error message on the last line indicates the problem. 

> ImportError: This package should not be accessible on Python 3.

Your setup is mixing python3 and python2.7.
Regards,
Andrew

**Comment by yjx1217** [comment]
Hi Andrew,

Is there any easy way to get around this problem? Thanks!

Best,
Jia-Xing
