### ISSUE TITLE
circlator.assembly.Error

### ISSUE THREAD

**Issue by a1204350** [sanger-pathogens/circlator#95]
Hi, there
I tested circlator with test command and it worked perfect. However, when I entered the following commands
circlator all --verbose --threads 8 --merge_min_id 85 --merge_breaklen 1000 96200minion_mc10.fasta minion_trimmedReads.fasta ./spades/
it stopped at somewhere near "Making ACT files from 04.merge.merge.iter.2.merged.fasta"

please see the detailed information below

_________________________ Checking external programs __________________________
Circlator version: 1.5.1

External dependencies:
bwa	0.7.15	/home/linuxbrew/.linuxbrew/bin/bwa
canu	1.5	/home/linuxbrew/.linuxbrew/bin/canu
nucmer	3.1	/home/linuxbrew/.linuxbrew/bin/nucmer
prodigal	2.6.2	/home/linuxbrew/.linuxbrew/bin/prodigal
samtools	1.4.1	/home/linuxbrew/.linuxbrew/bin/samtools
WARNING: SPAdes version 3.10.1 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
spades	3.10.1	/home/linuxbrew/.linuxbrew/bin/spades.py

Python version:
3.6.1 (default, Apr  8 2017, 07:19:26) 
[GCC 4.8.4]

Python dependencies:
openpyxl	2.4.1	/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/openpyxl/__init__.py
pyfastaq	3.14.0	/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/pyfastaq/__init__.py
pymummer	0.10.1	/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/pymummer/__init__.py
pysam	0.8.4	/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/pysam/__init__.py
WARNING: SPAdes version 3.10.1 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
______________________________ Running mapreads _______________________________
samtools	1.4.1	/home/linuxbrew/.linuxbrew/bin/samtools
bwa	0.7.15	/home/linuxbrew/.linuxbrew/bin/bwa
syscall: bwa index -p 01.mapreads.bam.tmp.bwa_index 00.input_assembly.fasta
syscall: bwa mem -x pacbio -t 8 01.mapreads.bam.tmp.bwa_index /home/zong/Desktop/666/96200/circlator/minion_trimmedReads.fasta | samtools view -F 0x0800 -T 00.input_assembly.fasta -b -o 01.mapreads.bam.tmp.unsorted.bam -
syscall: samtools sort -@ 4 -m 125M 01.mapreads.bam.tmp.unsorted.bam -o 01.mapreads.bam
syscall: samtools index 01.mapreads.bam
______________________________ Running bam2reads ______________________________
Getting reads from BAM file /home/zong/Desktop/666/96200/circlator/spades/01.mapreads.bam
Getting all reads that map to ends of contig 96200minion_mc10_1. Coords: 1-50000;5022640-5072639
Getting all reads that map to contig 96200minion_mc10_10
Getting all reads that map to contig 96200minion_mc10_11
Getting all reads that map to contig 96200minion_mc10_12
Getting all reads that map to contig 96200minion_mc10_13
Getting all reads that map to contig 96200minion_mc10_14
Getting all reads that map to contig 96200minion_mc10_15
Getting all reads that map to contig 96200minion_mc10_16
Getting all reads that map to contig 96200minion_mc10_17
Getting all reads that map to contig 96200minion_mc10_18
Getting all reads that map to contig 96200minion_mc10_19
Getting all reads that map to ends of contig 96200minion_mc10_2. Coords: 1-50000;113721-163720
Getting all reads that map to contig 96200minion_mc10_20
Getting all reads that map to contig 96200minion_mc10_21
Getting all reads that map to contig 96200minion_mc10_22
Getting all reads that map to contig 96200minion_mc10_23
Getting all reads that map to contig 96200minion_mc10_24
Getting all reads that map to contig 96200minion_mc10_25
Getting all reads that map to contig 96200minion_mc10_26
Getting all reads that map to contig 96200minion_mc10_27
Getting all reads that map to contig 96200minion_mc10_28
Getting all reads that map to contig 96200minion_mc10_29
Getting all reads that map to ends of contig 96200minion_mc10_3. Coords: 1-50000;54749-104748
Getting all reads that map to contig 96200minion_mc10_30
Getting all reads that map to contig 96200minion_mc10_31
Getting all reads that map to contig 96200minion_mc10_32
Getting all reads that map to contig 96200minion_mc10_33
Getting all reads that map to contig 96200minion_mc10_34
Getting all reads that map to contig 96200minion_mc10_35
Getting all reads that map to contig 96200minion_mc10_36
Getting all reads that map to contig 96200minion_mc10_37
Getting all reads that map to contig 96200minion_mc10_38
Getting all reads that map to contig 96200minion_mc10_4
Getting all reads that map to contig 96200minion_mc10_5
Getting all reads that map to contig 96200minion_mc10_6
Getting all reads that map to contig 96200minion_mc10_7
Getting all reads that map to contig 96200minion_mc10_8
Getting all reads that map to contig 96200minion_mc10_9
Getting all unmapped reads
Finished getting reads.
Log file: /home/zong/Desktop/666/96200/circlator/spades/02.bam2reads.log
Reads file: /home/zong/Desktop/666/96200/circlator/spades/02.bam2reads.fasta
______________________________ Running assemble _______________________________
samtools	1.4.1	/home/linuxbrew/.linuxbrew/bin/samtools
WARNING: SPAdes version 3.10.1 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
spades	3.10.1	/home/linuxbrew/.linuxbrew/bin/spades.py
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/02.bam2reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.127.zja_p98v -t 8 -k 127 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.127.zja_p98v/contigs.fasta
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/02.bam2reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.117.zl1gtppk -t 8 -k 117 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.117.zl1gtppk/contigs.fasta
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/02.bam2reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.107.t_iaspce -t 8 -k 107 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.107.t_iaspce/contigs.fasta
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/02.bam2reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.97.4_cfct66 -t 8 -k 97 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.97.4_cfct66/contigs.fasta
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/02.bam2reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.87.wuyfga3j -t 8 -k 87 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.87.wuyfga3j/contigs.fasta
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/02.bam2reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.77.1_sat3zg -t 8 -k 77 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/03.assemble.tmp.spades.77.1_sat3zg/contigs.fasta
[assemble]	kmer	N50
[assemble]	77	53776
[assemble]	87	53792
[assemble]	97	37763
[assemble]	107	39658
[assemble]	117	44019
[assemble]	127	53758
[assemble] using assembly with kmer 87
________________________________ Running merge ________________________________
Running command: bash run_nucmer.sh
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "p.ntref" of length 6680340
# construct suffix tree for sequence of length 6680340
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 66803 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /home/linuxbrew/.linuxbrew/Cellar/mummer/3.23_1/mummer p.ntref 2.84
# reading input file "/home/zong/Desktop/666/96200/circlator/spades/03.assemble/contigs.fasta" of length 1067392
# matching query-file "/home/zong/Desktop/666/96200/circlator/spades/03.assemble/contigs.fasta"
# against subject-file "p.ntref"
# COMPLETETIME /home/linuxbrew/.linuxbrew/Cellar/mummer/3.23_1/mummer p.ntref 3.81
# SPACE /home/linuxbrew/.linuxbrew/Cellar/mummer/3.23_1/mummer p.ntref 7.51
4: FINISHING DATA

Making ACT files from 00.input_assembly.fasta /home/zong/Desktop/666/96200/circlator/spades/03.assemble/contigs.fasta 04.merge.merge.iter.1.coords
samtools	1.4.1	/home/linuxbrew/.linuxbrew/bin/samtools
bwa	0.7.15	/home/linuxbrew/.linuxbrew/bin/bwa
syscall: bwa index -p 04.merge.merge.iter.2.bam.tmp.bwa_index 04.merge.merge.iter.2.merged.fasta
syscall: bwa mem -x pacbio -t 8 04.merge.merge.iter.2.bam.tmp.bwa_index 02.bam2reads.fasta | samtools view -F 0x0800 -T 04.merge.merge.iter.2.merged.fasta -b -o 04.merge.merge.iter.2.bam.tmp.unsorted.bam -
syscall: samtools sort -@ 4 -m 125M 04.merge.merge.iter.2.bam.tmp.unsorted.bam -o 04.merge.merge.iter.2.bam
syscall: samtools index 04.merge.merge.iter.2.bam
samtools	1.4.1	/home/linuxbrew/.linuxbrew/bin/samtools
WARNING: SPAdes version 3.10.1 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
spades	3.10.1	/home/linuxbrew/.linuxbrew/bin/spades.py
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.127.4ujuu8og -t 8 -k 127 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.127.4ujuu8og/contigs.fasta
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.117.xprip4ey -t 8 -k 117 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.117.xprip4ey/contigs.fasta
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.107.nfcjenuc -t 8 -k 107 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.107.nfcjenuc/contigs.fasta
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.97.8ormd5qy -t 8 -k 97 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.97.8ormd5qy/contigs.fasta
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.87.v4phbqci -t 8 -k 87 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.87.v4phbqci/contigs.fasta
syscall: spades.py -s /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.reads.fasta -o /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.77.ljnbbsrb -t 8 -k 77 --careful --only-assembler
syscall: samtools faidx /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly.tmp.spades.77.ljnbbsrb/contigs.fasta
[assemble]	kmer	N50
[assemble]	77	55319
[assemble]	87	55381
[assemble]	97	37763
[assemble]	107	39658
[assemble]	117	53751
[assemble]	127	53758
[assemble] using assembly with kmer 87
Running command: bash run_nucmer.sh
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "p.ntref" of length 6669533
# construct suffix tree for sequence of length 6669533
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 66695 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /home/linuxbrew/.linuxbrew/Cellar/mummer/3.23_1/mummer p.ntref 2.69
# reading input file "/home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly/contigs.fasta" of length 1188473
# matching query-file "/home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly/contigs.fasta"
# against subject-file "p.ntref"
# COMPLETETIME /home/linuxbrew/.linuxbrew/Cellar/mummer/3.23_1/mummer p.ntref 3.77
# SPACE /home/linuxbrew/.linuxbrew/Cellar/mummer/3.23_1/mummer p.ntref 7.62
4: FINISHING DATA

Making ACT files from 04.merge.merge.iter.2.merged.fasta /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly/contigs.fasta 04.merge.merge.iter.2.coords
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/circlator", line 58, in <module>
    exec('circlator.tasks.' + task + '.run()')
  File "<string>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/circlator/tasks/all.py", line 212, in run
    m.run()
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/circlator/merge.py", line 825, in run
    self._circularise_contigs(nucmer_hits)
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/circlator/merge.py", line 351, in _circularise_contigs
    called_as_circular_by_spades = self.reassembly.circular_contigs()
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/circlator/assembly.py", line 183, in circular_contigs
    return self._circular_contigs_from_spades_after_3_6_1(self.assembly_graph_fastg, self.contigs_paths)
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/circlator/assembly.py", line 129, in _circular_contigs_from_spades_after_3_6_1
    paths_dict = Assembly._spades_contigs_paths_to_dict(contigs_paths)
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/circlator/assembly.py", line 106, in _spades_contigs_paths_to_dict
    raise Error('Error loading info from SPAdes contigs path file ' + filename)
circlator.assembly.Error: Error loading info from SPAdes contigs path file /home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly/contigs.paths

Could someone help me to solve this? Thanks so much.

Circlator version: 1.5.1

External dependencies:
bwa	0.7.15	/home/linuxbrew/.linuxbrew/bin/bwa
canu	1.5	/home/linuxbrew/.linuxbrew/bin/canu
nucmer	3.1	/home/linuxbrew/.linuxbrew/bin/nucmer
prodigal	2.6.2	/home/linuxbrew/.linuxbrew/bin/prodigal
samtools	1.4.1	/home/linuxbrew/.linuxbrew/bin/samtools
WARNING: SPAdes version 3.10.1 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.
spades	3.10.1	/home/linuxbrew/.linuxbrew/bin/spades.py

Python version:
3.6.1 (default, Apr  8 2017, 07:19:26) 
[GCC 4.8.4]

Python dependencies:
openpyxl	2.4.1	/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/openpyxl/__init__.py
pyfastaq	3.14.0	/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/pyfastaq/__init__.py
pymummer	0.10.1	/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/pymummer/__init__.py
pysam	0.8.4	/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.1/libexec/lib/python3.6/site-packages/pysam/__init__.py

**Comment by martinghunt** [comment]
Could you copy + paste the contents of `/home/zong/Desktop/666/96200/circlator/spades/04.merge.merge.iter.2.assembly/contigs.paths` here please?

**Comment by a1204350** [comment]
it seems like I didn't save that folder, anyway I ran it with canu as the assembler and it went well without any error. I checked the spade log file and found it saying the reads I used were at poor quality and failed the reads error correction. Maybe this was the reason? Thanks
